# Generated by Django 6.0.5 on 2026-09-17 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='Pintle Solutions', max_length=250)),
                ('slogan', models.CharField(blank=True, default='Excellence in Education', max_length=250)),
                ('current_session', models.CharField(default='2025/2026', max_length=20)),
                ('current_term', models.CharField(default='First Term', max_length=20)),
                ('dashboard_bg', models.ImageField(blank=True, null=True, upload_to='dashboard_bg/')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'School Setting',
                'verbose_name_plural': 'School Settings',
            },
        ),
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='classroom',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['-date_recorded']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date_paid']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['full_name']},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='school.student'),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('parent', 'Parent'), ('student', 'Student')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='school.classroom'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='school.course'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='school.student'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date_paid',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='school.student'),
        ),
        migrations.AlterField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='school.classroom'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subjectassignment',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='school.classroom'),
        ),
        migrations.AlterField(
            model_name='subjectassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='school.teacher'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='school.classroom'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('classroom', 'day', 'period')},
        ),
    ]
